cc_library(
    name = "lib",
    srcs = glob(["**/*.cc"]),
    hdrs = glob(["**/*.hh"]),
    visibility = ["//visibility:public"],
)

#cc_library(
#	name = "InteractableObject",
#	srcs = ["InteractableObject.cc"]
#)
