#ifndef TBGE_TERMINAL_BOX_DRAWING_BOX_DRAWING_CONSTANTS_H_
#define TBGE_TERMINAL_BOX_DRAWING_BOX_DRAWING_CONSTANTS_H_

#include <map>
#include <string_view>

namespace tbge {
namespace terminal {
enum Line {
  kLeftRight,
  kBBLeftRight,
  kUpDown,
  kBBUpDown,
  kLeftRightTrippleDash,
  kBBLeftRightTrippleDash,
  kUpDownTrippleDash,
  kBBUpDownTrippleDash,
  kLeftRightQuadrupleDash,
  kBBLeftRightQuadrupleDash,
  kUpDownQuadrupleDash,
  kBBUpDownQuadrupleDash,
  kDownRight,
  kDownBRight,
  kBDownRight,
  kBBDownRight,
  kDownLeft,
  kDownBLeft,
  kBDownLeft,
  kBBDownLeft,
  kUpRight,
  kUpBRight,
  kBUpRight,
  kBBUpRight,
  kUpLeft,
  kUpBLeft,
  kBUpLeft,
  kBBUpLeft,
  kUpDownRight,
  kUpDownBRight,
  kBUpDownRight,
  kUpBDownRight,
  kBUpBDownRight,
  kBUpDownBRight,
  kUpBDownBRight,
  kBBUpDownRight,
  kUpDownLeft,
  kUpDownBLeft,
  kBUpDownLeft,
  kUpBDownLeft,
  kBUpBDownLeft,
  kBUpDownBLeft,
  kUpBDownBLeft,
  kBBUpDownLeft,
  kDownLeftRight,
  kDownBLeftRight,
  kDownLeftBRight,
  kDownBLeftBRight,
  kBDownLeftRight,
  kBDownBLeftRight,
  kBDownLeftBRight,
  kBBDownLeftRight,
  kUpLeftRight,
  kUpBLeftRight,
  kUpLeftBRight,
  kUpBLeftBRight,
  kBUpLeftRight,
  kBUpBLeftRight,
  kBUpLeftBRight,
  kBBUpLeftRight,
  kUpDownLeftRight,
  kUpDownBLeftRight,
  kUpDownLeftBRight,
  kUpDownBLeftBRight,
  kBUpDownLeftRight,
  kUpBDownLeftRight,
  kBUpBDownLeftRight,
  kBUpDownBLeftRight,
  kBUpDownLeftBRight,
  kUpBDownBLeftRight,
  kUpBDownLeftBRight,
  kBUpDownBLeftBRight,
  kUpBDownBLeftBRight,
  kBUpBDownBLeftRight,
  kBUpBDownLeftBRight,
  kBBUpDownLeftRight,
  kLeftRightDoubleDash,
  kBBLeftRightDoubleDash,
  kUpDownDoubleDash,
  kBBUpDownDoubleDash,
  kDDLeftRight,
  kDDUpDown,
  kDownDRight,
  kDDownRight,
  kDDDownRight,
  kDownDLeft,
  kDDownLeft,
  kDDDownLeft,
  kUpDRight,
  kDUpRight,
  kDDUpRight,
  kUpDLeft,
  kDUpLeft,
  kDDUpLeft,
  kUpDownDRight,
  kDUpDDownRight,
  kDDUpDownRight,
  kUpDownDLeft,
  kDUpDDownLeft,
  kDDUpDownLeft,
  kDownDLeftDRight,
  kDDownLeftRight,
  kDDDownLeftRight,
  kUpDLeftDRight,
  kDUpLeftRight,
  kDDUpLeftRight,
  kUpDownDLeftDRight,
  kDUpDDownLeftRight,
  kDDUpDownLeftRight,
  kDownRightCurve,
  kDownLeftCurve,
  kUpLeftCurve,
  kUpRightCurve,
  kDiagonalBottomLeftTopRight,
  kDiagonalTopLeftBottomRight,
  kDiagonalCross,
  kLeft,
  kUp,
  kRight,
  kDown,
  kBLeft,
  kBUp,
  kBRight,
  kBDown,
  kLeftBRight,
  kUpBDown,
  kBLeftRight,
  kBUpDown,
};

enum Box {
  kUpperHalf,
  kLowerOneEigth,
  kLowerOneQuarter,
  kLowerThreeEights,
  kLowerHalf,
  kLowerFiveEights,
  kLowerThreeQuarters,
  kLowerSevenEights,
  kFull,
  kLeftSevenEights,
  kLeftThreeQuarters,
  kLeftFiveEights,
  kLeftHalf,
  kLeftThreeEights,
  kLeftOneQuarter,
  kLeftOneEigth,
  kRightHalf,
  kLightShade,
  kMediumShade,
  kDarkShade,
  kUpperOneEight,
  kRightOneEight,
  kQuadrantLowerLeft,
  kQuadrantLowerRight,
  kQuadrantUpperLeft,
  kQuadrantUpperLeftLowerLeftLowerRight,
  kQuadrantUpperLeftLowerRigth,
  kQuadrantUpperLeftUpperRightLowerLeft,
  kQuadrantUpperLeftUpperRightLowerRight,
  kQuadrantUpperRight,
  kQuadrantUpperRightLowerLeft,
  kQuadrantUpperRightLowerLeftLowerRight,
};

const std::map<Line, std::u8string_view> kLineMap{
    {Line::kLeftRight, u8"\u2500"},
    {Line::kLeftRight, u8"\u2501"},
    {Line::kUpDown, u8"\u2502"},
    {Line::kUpDown, u8"\u2503"},
};
}  // namespace terminal
}  // namespace tbge

#endif  // TBGE_TERMINAL_BOX_DRAWING_BOX_DRAWING_CONSTANTS_H_
