# BUILD file for box drawing utilities
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "box_drawing",
    hdrs = glob(["*.h"]),
)
