# BUILD file for components library
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "location",
    hdrs = ["location.h"],
    deps = [
        "//src/ecs:ecs",
    ],
)

cc_library(
    name = "exit",
    hdrs = ["exit.h"],
    deps = [
        "//src/ecs:ecs",
    ],
)

cc_library(
    name = "player",
    hdrs = ["player.h"],
    deps = [
        "//src/ecs:ecs",
    ],
)
