# BUILD file for ECS context module
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "context",
    hdrs = ["context.h"],
)
